from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO
from datetime import datetime

class PDFService:
    def generate_invoice(self, data: dict, type: str = "INVOICE") -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4)
        elements = []
        styles = getSampleStyleSheet()

        # Define custom styles
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#2563eb"),
            spaceAfter=12
        )
        
        header_style = ParagraphStyle(
            'Header',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.gray
        )

        # --- Header Section ---
        elements.append(Paragraph(f"OpenGate ERP - {type}", title_style))
        elements.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", header_style))
        elements.append(Paragraph(f"Reference: {data.get('id', 'N/A')}", header_style))
        
        # Support both 'customer' and 'customer_name'
        customer = data.get("customer") or data.get("customer_name")
        if customer:
            elements.append(Paragraph(f"Customer: {customer}", header_style))
            
        # Support both 'vendor' and 'supplier_name'
        vendor = data.get("vendor") or data.get("supplier_name")
        if vendor:
             elements.append(Paragraph(f"Vendor: {vendor}", header_style))
        
        elements.append(Spacer(1, 0.5 * inch))

        # --- Items Table ---
        # Table Header
        table_data = [['Item', 'Qty', 'Price', 'Total']]
        
        # Table Rows
        total_amount = 0
        # Support both 'items' and 'lines'
        items = data.get('items') or data.get('lines', [])
        
        for item in items:
            # Handle different field names for qty and price
            try:
                raw_qty = item.get('quantity') or item.get('qty', 0)
                raw_price = item.get('unit_price') or item.get('price', 0)
                qty = float(raw_qty)
                price = float(raw_price)
                total = qty * price
                total_amount += total
                
                # Handle different field names for item name
                name = item.get('item_name') or item.get('name', 'Unknown Item')
                
                table_data.append([
                    name,
                    f"{qty:,.2f}",
                    f"${price:,.2f}",
                    f"${total:,.2f}"
                ])
            except (ValueError, TypeError):
                continue
            
        # Total Row
        table_data.append(['', '', 'Grand Total:', f"${total_amount:,.2f}"])

        # Create Table
        table = Table(table_data, colWidths=[3 * inch, 1 * inch, 1.5 * inch, 1.5 * inch])
        
        # Style Table
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#1e293b")),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'), # Align items left
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor("#f8fafc")), # Footer background
            ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -2), 1, colors.HexColor("#e2e8f0")),
            ('LINEBELOW', (0, -1), (-1, -1), 2, colors.HexColor("#2563eb")),
        ]))

        elements.append(table)
        elements.append(Spacer(1, 0.5 * inch))

        # --- Footer / Signature Section ---
        elements.append(Paragraph("Authorized Signature:", styles['Heading4']))
        elements.append(Spacer(1, 0.3 * inch))
        elements.append(Paragraph("___________________________", styles['Normal']))
        elements.append(Paragraph(f"Generated by: {data.get('created_by_email', 'Admin')}", styles['Normal']))
        elements.append(Paragraph("OpenGate ERP System", styles['Italic']))

        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()
